version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx-mic.conf:/etc/nginx/nginx.conf:ro

  microservice1-1:
    build:
      context: ./Microservice1
      dockerfile: Dockerfile
    container_name: microservice1-1
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=8001
      - PORT=8001
      - HOST1=http://microservice2-1:8011
      - HOST2=http://microservice2-2:8012
      - HOST3=http://microservice2-3:8013
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice1-2:
    build:
      context: ./Microservice1
      dockerfile: Dockerfile
    container_name: microservice1-2
    ports:
      - "8002:8002"
    environment:
      - SERVER_PORT=8002
      - PORT=8002
      - HOST1=http://microservice2-1:8011
      - HOST2=http://microservice2-2:8012
      - HOST3=http://microservice2-3:8013
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice1-3:
    build:
      context: ./Microservice1
      dockerfile: Dockerfile
    container_name: microservice1-3
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=8003
      - PORT=8003
      - HOST1=http://microservice2-1:8011
      - HOST2=http://microservice2-2:8012
      - HOST3=http://microservice2-3:8013
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice2-1:
    build:
      context: ./Microservice2
      dockerfile: Dockerfile
    container_name: microservice2-1
    ports:
      - "8011:8011"
    environment:
      - SERVER_PORT=8011
      - PORT=8011
      - HOST1=http://microservice3-1:8021
      - HOST2=http://microservice3-2:8022
      - HOST3=http://microservice3-3:8023
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice2-2:
    build:
      context: ./Microservice2
      dockerfile: Dockerfile
    container_name: microservice2-2
    ports:
      - "8012:8012"
    environment:
      - SERVER_PORT=8012
      - PORT=8012
      - HOST1=http://microservice3-1:8021
      - HOST2=http://microservice3-2:8022
      - HOST3=http://microservice3-3:8023
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice2-3:
    build:
      context: ./Microservice2
      dockerfile: Dockerfile
    container_name: microservice2-3
    ports:
      - "8013:8013"
    environment:
      - SERVER_PORT=8013
      - PORT=8013
      - HOST1=http://microservice3-1:8021
      - HOST2=http://microservice3-2:8022
      - HOST3=http://microservice3-3:8023
      - HOST_NUM=3
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice3-1:
    build:
      context: ./Microservice3
      dockerfile: Dockerfile
    container_name: microservice3-1
    ports:
      - "8021:8021"
    environment:
      - SERVER_PORT=8021
      - PORT=8021
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice3-2:
    build:
      context: ./Microservice3
      dockerfile: Dockerfile
    container_name: microservice3-2
    ports:
      - "8022:8022"
    environment:
      - SERVER_PORT=8022
      - PORT=8022
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  microservice3-3:
    build:
      context: ./Microservice3
      dockerfile: Dockerfile
    container_name: microservice3-3
    ports:
      - "8023:8023"
    environment:
      - SERVER_PORT=8023
      - PORT=8023
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
