version: '3.8'

services:
  monolith:
    build:
      context: ./Monolith
      dockerfile: Dockerfile
    container_name: monolith
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=8001
      - PORT=8001